name: build and deploy docs

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC to keep companion microsites updated e.g. swift SDK docs

jobs:
  publish-docs-from-container:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    env:
      GIT_BRANCH: main
      gh_ci_key: ${{ secrets.gh_ci_key }}
      ziti_ci_gpg_key: ${{ secrets.ZITI_CI_GPG_KEY }}
      ziti_ci_gpg_key_id: ${{ secrets.ZITI_CI_GPG_KEY_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: generate docs
        run: ./publish.sh
