name: build and deploy docs

on:
  push:
    branches:
      - master

jobs:
  publish-docs-from-container:
    runs-on: ubuntu-latest
    container:
      image: openziti/doc:docfx
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
        AWS_DEFAULT_REGION: us-east-1
        GIT_BRANCH: master
        gh_ci_key: ${{ secrets.gh_ci_key }}
    steps:
      - uses: actions/checkout@v1
      #- name: Install Ziti CI
      #  uses: netfoundry/ziti-ci@v1
      #- run: ls -l /
      #- run: ls -l /ziti-doc
      #- run: pwd
      #- run: ls ./docfx_project
      #- run: find . -name docfx.json
      #- run: mono --version
      - name: generate docs
        run: ./publish.sh
      - run: git status
         
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_NAME: openziti/openziti.github.io
          BRANCH: master # The branch the action should deploy to.
          FOLDER: openziti.github.io # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch