name: build and deploy docs

on:
  push:
    branches:
      - master

jobs:
  publish-docs-from-container:
    runs-on: ubuntu-latest
    container:
      image: openziti/doc:docfx
    steps:
      - uses: actions/checkout@v1
      - run: ls -l /
