name: build and deploy docs

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
      
jobs:
  publish-docs-from-container:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    container:
      image: openziti/doc:docfx
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
        AWS_DEFAULT_REGION: us-east-1
        GIT_BRANCH: master
        gh_ci_key: ${{ secrets.gh_ci_key }}
    steps:
      - uses: actions/checkout@v1
      - name: generate docs
        run: ./publish.sh
