name: build and deploy docs

on:
  push:
    branches:
      - master

jobs:
  publish-docs-from-container:
    runs-on: ubuntu-latest
    container:
      image: openziti/doc:docfx
      volumes:
        - ${{ github.workspace }}:/ziti-doc
    steps:
      - uses: actions/checkout@v1
      - run: ls -l /
      - run: ls -l /ziti-doc
      - run: pwd
      - run: ls ./docfx_project
      - run: find . -name docfx.json
      - run: mono --version
      - run: ./publish.sh
