name: ziti-mattermost-action-py
on:
  create:
  delete:
  issues:
  issue_comment:
  pull_request_review:
  pull_request_review_comment:
  pull_request:
  push:
  fork:
  release:
jobs:
  ziti-webhook:
    runs-on: ubuntu-latest
    name: Ziti Mattermost Action - Py
    steps:
    - uses: openziti/ziti-mattermost-action-py@main
      if: ${{ github.actor!= 'dependabot[bot]' && env.ZITI_MATTERMOST_WEBHOOK_URL != null }}
      with:
        zitiId: ${{ secrets.ZITI_MATTERMOST_IDENTITY }}
        webhookUrl: ${{ secrets.ZHOOK_URL }}
        eventJson: ${{ toJson(github.event) }}
        senderUsername: "GitHubZ"
        destChannel: "dev-notifications"
